import sqlite3

# 连接到 SQLite 数据库
conn = sqlite3.connect('database.db')

# 创建游标
cur = conn.cursor()

# 创建用户表
cur.execute('''
    CREATE TABLE IF NOT EXISTS USERS
    (UID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE,
    DORM TEXT NOT NULL,
    EMAIL TEXT);
''')

# 创建物品表
cur.execute('''
    CREATE TABLE IF NOT EXISTS ITEMS
    (IID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    BRAND TEXT,
    DESCRIPTION TEXT,
    QTY REAL NOT NULL,
    IS_CONSUME INTEGER);
''')

# 创建拥有关系表
cur.execute('''
    CREATE TABLE IF NOT EXISTS OWN
    (OID INTEGER PRIMARY KEY AUTOINCREMENT,
    UID INTEGER NOT NULL,
    IID INTEGER NOT NULL,
    FOREIGN KEY(UID) REFERENCES USERS ON DELETE CASCADE,
    FOREIGN KEY(IID) REFERENCES ITEMS ON DELETE CASCADE);
''')

# 创建分享表
cur.execute('''
    CREATE TABLE IF NOT EXISTS SHARE
    (SID INTEGER PRIMARY KEY AUTOINCREMENT,
    UID INTEGER NOT NULL,
    IID INTEGER NOT NULL,
    MODIFIED DATE NOT NULL,
    DDL DATE,
    FOREIGN KEY(UID) REFERENCES USERS ON DELETE CASCADE,
    FOREIGN KEY(IID) REFERENCES ITEMS ON DELETE CASCADE);
''')

# 创建标签表
cur.execute('''
    CREATE TABLE IF NOT EXISTS TAGS
    (NAME TEXT NOT NULL,
    IID INTEGER NOT NULL,
    FOREIGN KEY(IID) REFERENCES ITEMS ON DELETE CASCADE);
''')

# 创建功德表
cur.execute('''
    CREATE TABLE IF NOT EXISTS VIRTUE
    (UID INTEGER PRIMARY KEY NOT NULL UNIQUE,
    VIRTUE INTEGER NOT NULL,
    FOREIGN KEY(UID) REFERENCES USERS ON DELETE CASCADE);
''')

# 创建日志表
cur.execute('''
    CREATE TABLE IF NOT EXISTS VIRLOG
    (UID INTEGER NOT NULL,
    VIRLOG TEXT,
    FOREIGN KEY(UID) REFERENCES USERS ON DELETE CASCADE);
''')

# 插入数据
cur.execute("INSERT INTO USERS (NAME,DORM,EMAIL) VALUES ('ANDY', '405', '1755331362@QQ.COM')")
cur.execute("INSERT INTO USERS (NAME,DORM) VALUES ('CHEN', '格致园皇帝宿舍')")
cur.execute("INSERT INTO VIRTUE (UID,VIRTUE) VALUES (1, 0 )")

# 查询结果
cur.execute("SELECT SID, UID, IID, MODIFIED, DDL FROM SHARE")
rows = cur.fetchall()
for row in rows:
   print("SID = ", row[0])
   print("MODIFIED = ", row[3])
   print("DDL = ", row[4])

# 提交事务
conn.commit()

# 关闭连接
conn.close()
